[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_port = COM3

; Upload settings
upload_speed = 921600
upload_port = COM3

; Build flags
build_flags =
    -DBUILD_FLAG_TEST
