[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DWEATHER_LOCATION_LAT=31.23
    -DWEATHER_LOCATION_LON=121.47
    -DWEATHER_LOCATION_NAME=Shanghai
    -DTZ_OFFSET=28800

lib_deps =
    tzapu/WiFiManager @ 2.0.17
    me-no-dev/ESPAsyncWebServer @ 3.6.0
    me-no-dev/ESPAsyncTCP @ ^1.2.2
    bblanchon/ArduinoJson @ ^6.21.5
