[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DWEATHER_LOCATION_LAT=31.23
    -DWEATHER_LOCATION_LON=121.47
    -DTZ_OFFSET=28800
    -DBACKEND_HOST=\"192.168.3.11\"
    -DBACKEND_PORT=3001

lib_deps =
    tzapu/WiFiManager @ 2.0.17
    bblanchon/ArduinoJson @ ^6.21.5
